config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bookings, only: [:show, :create, :destroy] do
      resources :payments, only: :new
  end

  resources :users do
    resources :bookings, only: [:show, :index, :destroy]
  end

  root to: 'pages#home'
  resources :cars

  # Adding  API routes
   namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :cars, only: [ :index, :show, :update, :create, :destroy ]
    end
  end



  #added address from ngrok maybe the URL not should be there
    mount StripeEvent::Engine, at: '/stripe-webhooks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  #stripe
  monetize :amount_cents

  private

  def refund
    refund = Stripe::Refund.create({
    charge: self.amount_cents,
    amount: self.amount_cents
  })

  end

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  #validations
  validates :name, presence: true
  validates :category, inclusion: { in: %w(Económico SUV Monovolúmenes),
    message: "%{value} is not a valid category" }
  validates :doors, inclusion: { in: 2..5 }
  validates :seats, inclusion: { in: 2..5 }
  validates :gearshift, inclusion: { in: %W(manual automatic), message: "%{value} is not a valid gearshift" }
  validates :air, presence: true # maybe I have to check this out
  validates :lagguage, presence: true
  validates :pick_up, presence: true
  validates :start_date, presence: true
  #validates end_date, presence true
  validate :end_date_is_before_start_date

 #photo uploader
  mount_uploader :image, PhotoUploader

  #money rails
    monetize :price_cents


   extend TimeSplitter::Accessors
  split_accessor :start_date

  private

  def end_date_is_before_start_date
    return if end_date.blank? || start_date.blank?

  if end_date < start_date
    errors.add(:end_date, "cannot be before the start date")
  end
end




end

app/models/user.rb
class User < ApplicationRecord
      has_many :cars, dependent: :destroy
      has_many :bookings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #for API
  acts_as_token_authenticatable

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from StandardError,                with: :internal_server_error
  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def internal_server_error(exception)
    if Rails.env.development?
      response = { type: exception.class.to_s, message: exception.message, backtrace: exception.backtrace }
    else
      response = { error: "Internal Server Error" }
    end
    render json: response, status: :internal_server_error
  end
end

app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User, except: [ :index, :show ]
  before_action :set_car, only: [ :show, :update, :destroy ]


  def index
    @cars = policy_scope(Car)
  end

  def update
    if @car.update(car_params)
      render :show
    else
      render_error
    end

  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car
    if @car.save
      render :show, status: :created
    else
      render_error
      end
  end

  end

  def destroy
    @car.destroy
    head :no_content #404

  end

    private

  def set_car
    @car = Car.find(params[:id])
    authorize @car  # For Pundit
  end

 def car_params
    params.require(:car).permit(:name, :image, :category, :doors , :seats, :gearshift, :air, :lagguage, :pick_up, :start_date, :end_date)

  end

  def render_error
    render json: { errors: @car.errors.full_messages },
      status: :unprocessable_entity
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

   include Pundit
    after_action :verify_authorized, except: :index,  unless: :skip_pundit?

    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

     rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
   def user_not_authorized
     flash[:alert] = "You are not authorized to perform this action."
     redirect_to(root_path)
   end

    private

    def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/



    end



end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
   skip_before_action :authenticate_user!, only: [:index, :show]

   def index
    @bookings = policy_scope(Booking)
    authorize @bookings


   end

  def create
    car = Car.find(params[:car_id])

   @booking = Booking.create!(car: car, car_sku: car.sku, amount: car.price, state: 'pending', user: current_user, photo: car.image )
   authorize @booking


  session = Stripe::Checkout::Session.create(
    payment_method_types: ['card'],
    line_items: [{
      name: car.sku,
      images: [car.image],
      amount: car.price_cents.to_i,
      currency: 'eur',
      quantity: 1

    }],
    success_url: booking_url(@booking),
    cancel_url: booking_url(@booking)
  )

  @booking.update(checkout_session_id: session.id)
  redirect_to new_booking_payment_path(@booking)


end

def show

  @booking = current_user.bookings.find(params[:id])
  authorize @booking
end



def destroy

  @booking = Booking.find(params[:id])
  @booking.destroy
  authorize @booking
  redirect_to  cars_path
end




end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show,:edit,:update, :destroy]
  skip_before_action :authenticate_user!, only: [:index,:show]


  def index

   @cars = policy_scope(Car).order(created_at: :desc)
   case

   when
    params[:query].present?

    @cars = Car.where("pick_up ILIKE ?", "%#{params[:query]}%")
    #@cars = Car.search(params[:query])

    when
    params[:start_date].present? && params[:end_date].present?
    @query = params[:start_date]&& params[:end_date]
    @cars = Car.where("start_date >= ? and end_date <= ?", params[:start_date], params[:end_date])

    when params[:start_date].present?
      @query = params[:start_date]
      @cars = Car.where("start_date >= ?",params[:start_date])

    when params[:end_date].present?

     @query = params[:end_date]
      @cars = Car.where("end_date >= ?",params[:end_date])

      else

        @cars = Car.all

    end


  end

  def show


  end

  def new
    @car = Car.new
    authorize @car

  end

  def create

   #@car = current_user.cars.build(car_params)
   @car = Car.new(car_params)
   @car.user = current_user
   authorize @car

    if @car.save
      redirect_to car_path(@car), notice: 'car was created'
      else
      render :new
    end
  end

  def edit


  end

  def update

    @car.updte(car_params)

  end

  def destroy

    @car.destroy

    redirect_to cars_path

  end

  private


  def car_params
    params.require(:car).permit(:name, :image, :category, :doors , :seats, :gearshift, :air, :lagguage, :sku ,:pick_up, :start_date, :end_date)

  end

  def set_car
    authorize @car = Car.find(params[:id])

  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home

  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
    @booking = current_user.bookings.where(state: 'pending').find(params[:booking_id])
    authorize @booking
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Your bookings</h1>

<div class="container">

  <div class="row">
      <% @current_user.bookings.each do |booking| %>
    <div class="col-12 col-lg-8">
      <%= cl_image_tag booking.car.image, height: 300, width: 400, crop: :fill %>


    </div>

    <div class="col-12 col-lg-4">
      <h3> <%= booking.car.name%> </h3>
      <p> <%= booking.car.start_date %></p>
      <strong><%= booking.car.price %>€/día</strong>
      <p><%= booking.car.end_date %></p>
      <%= button_to "Cancel my book", booking, :data => { :confirm => "Are you sure?" }, :method => :delete, class: "btn btn-default " %>



    </div>
    <% end %>

  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">

      <h1>Order #<%= @booking.id %> <small><span class="badge badge-primary"><%= @booking.state %></span></small></h1>
      <%= cl_image_tag @booking.car.image, height: 300, width: 400, crop: :fill %>
      <ul class="list-unstyled">
        <li><strong>Book from</strong> <%= @booking.start_date %></li>
        <li><strong>CAR</strong> <%= @booking.car.name %> </li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @booking.amount %></li>
        </li>
      </ul>

    </div>
  </div>
</div>

app/views/cars/_form.html.erb
<% if @car.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

    <ul>
    <% @car.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>

<% end %>


<div class="container">

  <div class="row justify-content-center">

    <div class="col-md-8">
      <%= simple_form_for (@car) do |f| %>
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
    <%= f.input :doors %>
    <%= f.input :seats %>
    <%= f.input :gearshift %>
    <%= f.input :air %>
    <%= f.input :lagguage %>
    <%= f.input :pick_up %>
    <%= f.input :sku %>

    <div class="flex-container">
    <%= f.datetime_field :start_date, class: "fa fa-calendar"%>
    <%= f.datetime_field :end_date,  class: "fa fa-calendar" %>

    </div>

    <%= f.submit "create car", class: "btn btn-primary" %>
  <% end %>



    </div>
  </div>
</div>

app/views/cars/index.html.erb
<% if @query.present? %>
   <p>You searched for <strong><%= @query %></strong>. We found <%= @cars.count %> cars out of our <%= Car.count %> on our website.</p>

<% end %>

<div class="main-container">

<div class="cards">
    <% @cars.each do |car| %>
   <div class="card">
   <%= link_to car.name, car_path(car)  %>
    <%= cl_image_tag car.image, height: 50, width: 300, crop: :fill %>
    <div class="flexx-container">
      <a><img src="https://img.icons8.com/windows/32/000000/airbag-off.png"><%= car.seats %></a>
      <a><img src="https://img.icons8.com/material-sharp/24/000000/car-door--v2.png"><%= car.doors %></a>
      <a><img src="https://img.icons8.com/small/24/000000/cooling.png"><%= car.air %></a>
      <a><img src="https://img.icons8.com/ios/30/000000/bag-diagonal-view.png"><%= car.lagguage %></a>


    </div>

       <% if policy(car).update? %>
        <%= link_to "Update ", edit_car_path(car) %>
        <% end %>
        <% if policy(car).destroy? %>
        <%= link_to "destroy", car, method: :delete, data: {confirm: 'are you sure?'} %>
        <% end %>




  </div>
    <% end %>


</div>


</div>

<a href="https://icons8.com/icon/32148/door">Door icon by Icons8</a>

app/views/cars/new.html.erb
<h1>create your car</h1>
<%= render 'form' %>

app/views/cars/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-12 col-lg-8">
       <h1>Marca: <%= @car.name %></h1>
      <h2>Categoria: <%= @car.category %></h2>
      <p> Disponible desde <%= @car.start_date.strftime( "%d/%m/%Y %H:%M")%> Hasta <%= @car.end_date.strftime( "%d/%m/%Y %H:%M") %></p>
        <p>Amount: <%= humanized_money_with_symbol(@car.price) %></p>
        <p>Recogida en <%= @car.pick_up %></p>
        <p>Cambio: <%= @car.gearshift %></p>

       <%= form_tag bookings_path do %>
      <%= hidden_field_tag 'car_id', @car.id %>
      <%= submit_tag 'Book', class: 'btn btn-primary' %>
    <% end %>


    </div>

    <div class="col-12 col-lg-4">

      <%= cl_image_tag @car.image, height: 300, width: 400, crop: :fill %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

  <!-- FONT AWESOME
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    -->
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=847&q=80);">
  <div class="container">
    <h1>Try your future !</h1>

  </div>
</div>






<%= simple_form_for :search, url: cars_path, method: :get do |f| %>

<div class="flex-container">

  <div class="flex-item">

    <input class="form-control string required" type="text" name="query"  id="search_query" placeholder=" Try Murcia" />

  </div>

    <div class="flex-item">
      <label for="start">Start date:</label>
      <input id="date" type="date" name="start_date" id="search_query">


    </div>
      <div class="flex-item">
       <label for="start">End date:</label>
      <input id="date" type="date" name="end_date" id="search_query">


      </div>


  <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search">Search</i>
    </button>




</div>

<% end %>

app/views/payments/new.html.erb
<div class="container">
  <div class="row">

    <div class="col-12 col-lg-8">
      <h1>Checkout summary</h1>
      <p>Book of <strong><%= @booking.car.name %></strong> for <strong><%= humanized_money_with_symbol @booking.amount %></strong></p>
      <p>Recuerda que esta disponible desde <strong> <%= @booking.car.start_date %> </strong> </p>
      <p>hasta <%= @booking.car.end_date %></p>



      <button id="pay" class="btn btn-primary">Reservar!</button>

      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @booking.checkout_session_id %>'
          });
        });
      </script>
    </div>
    <div class="col-12 col-lg-4">
      <p>Select Start date
      <input id="date" type="date" name="start_date" id="search_query"></p>
       <p>Select end date
      <input id="date" type="date" name="start_date" id="search_query"></p>
        <%= cl_image_tag @booking.car.image, height: 300, width: 400, crop: :fill %>



    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p>CAR CMS</p>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>


        <li class="nav-item active">
          <%= link_to "Cars", cars_path, class: "nav-link" %>


        </li>
        <li class="nav-item-activee">
          <% if policy(Car).create? %>
          <%= link_to "New Car", new_car_path %>
          <% end %>

        </li>



        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/Nerfi", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">


            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

            <%= link_to "mis reservas", user_bookings_path(:user_session, user_session) %>

          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>